# /etc/starship.toml
# https://starship.rs/config/

format = '''
[┌](bold blue)[\[](bold blue)$all[\]](bold blue)
[└>](bold blue) '''

[line_break]
disabled = true

[character]
disabled = true

[username]
show_always = true
format = '[$user]($style) on '

[hostname]
ssh_only = false
